// Regenerates packages/orchestrator/src/assets/fonts.generated.ts from the .ttf
// files in that directory, embedding each as base64.
//
// Why: the orchestrator renders images with satori and needs the font bytes at
// runtime. Reading the .ttf from disk via import.meta.url breaks inside the Next
// serverless bundle (webpack rewrites the path / URL and Vercel's file tracer
// can't follow it), so we embed the bytes instead — identical behaviour in the
// Vercel function and the plain-node worker.
//
// Run after changing any font: `pnpm tsx scripts/embed-fonts.ts`.
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const assetsDir = join(dirname(fileURLToPath(import.meta.url)), "..", "packages", "orchestrator", "src", "assets");

const fonts: Record<string, string> = {
  anton: "anton.ttf",
  serif: "serif.ttf",
  interRegular: "inter-regular.ttf",
  interBold: "inter-bold.ttf",
};

let out =
  "// AUTO-GENERATED by scripts/embed-fonts.ts — do not edit by hand.\n" +
  "// Fonts are embedded as base64 so they load identically in the Next serverless\n" +
  "// bundle (no file tracing / import.meta.url path issues) and in the worker.\n\n";

for (const [name, file] of Object.entries(fonts)) {
  const b64 = readFileSync(join(assetsDir, file)).toString("base64");
  out += `export const ${name} = Buffer.from(\n  "${b64}",\n  "base64",\n);\n\n`;
}

writeFileSync(join(assetsDir, "fonts.generated.ts"), out);
console.log(`wrote fonts.generated.ts (${(Buffer.byteLength(out) / 1024).toFixed(0)} KB)`);
